# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie_driver/AddCrazyflieRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import crazyflie_driver.msg

class AddCrazyflieRequest(genpy.Message):
  _md5sum = "34565a892f53e550eb958f2ab393aeee"
  _type = "crazyflie_driver/AddCrazyflieRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string uri
string tf_prefix
float32 roll_trim
float32 pitch_trim
bool enable_logging
bool enable_parameters
LogBlock[] log_blocks
bool use_ros_time
bool enable_logging_imu
bool enable_logging_temperature
bool enable_logging_magnetic_field
bool enable_logging_pressure
bool enable_logging_battery
bool enable_logging_packets

================================================================================
MSG: crazyflie_driver/LogBlock
string topic_name
int16 frequency
string[] variables
"""
  __slots__ = ['uri','tf_prefix','roll_trim','pitch_trim','enable_logging','enable_parameters','log_blocks','use_ros_time','enable_logging_imu','enable_logging_temperature','enable_logging_magnetic_field','enable_logging_pressure','enable_logging_battery','enable_logging_packets']
  _slot_types = ['string','string','float32','float32','bool','bool','crazyflie_driver/LogBlock[]','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       uri,tf_prefix,roll_trim,pitch_trim,enable_logging,enable_parameters,log_blocks,use_ros_time,enable_logging_imu,enable_logging_temperature,enable_logging_magnetic_field,enable_logging_pressure,enable_logging_battery,enable_logging_packets

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddCrazyflieRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.uri is None:
        self.uri = ''
      if self.tf_prefix is None:
        self.tf_prefix = ''
      if self.roll_trim is None:
        self.roll_trim = 0.
      if self.pitch_trim is None:
        self.pitch_trim = 0.
      if self.enable_logging is None:
        self.enable_logging = False
      if self.enable_parameters is None:
        self.enable_parameters = False
      if self.log_blocks is None:
        self.log_blocks = []
      if self.use_ros_time is None:
        self.use_ros_time = False
      if self.enable_logging_imu is None:
        self.enable_logging_imu = False
      if self.enable_logging_temperature is None:
        self.enable_logging_temperature = False
      if self.enable_logging_magnetic_field is None:
        self.enable_logging_magnetic_field = False
      if self.enable_logging_pressure is None:
        self.enable_logging_pressure = False
      if self.enable_logging_battery is None:
        self.enable_logging_battery = False
      if self.enable_logging_packets is None:
        self.enable_logging_packets = False
    else:
      self.uri = ''
      self.tf_prefix = ''
      self.roll_trim = 0.
      self.pitch_trim = 0.
      self.enable_logging = False
      self.enable_parameters = False
      self.log_blocks = []
      self.use_ros_time = False
      self.enable_logging_imu = False
      self.enable_logging_temperature = False
      self.enable_logging_magnetic_field = False
      self.enable_logging_pressure = False
      self.enable_logging_battery = False
      self.enable_logging_packets = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.uri
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.tf_prefix
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f2B().pack(_x.roll_trim, _x.pitch_trim, _x.enable_logging, _x.enable_parameters))
      length = len(self.log_blocks)
      buff.write(_struct_I.pack(length))
      for val1 in self.log_blocks:
        _x = val1.topic_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_h().pack(val1.frequency))
        length = len(val1.variables)
        buff.write(_struct_I.pack(length))
        for val2 in val1.variables:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.pack('<I%ss'%length, length, val2))
      _x = self
      buff.write(_get_struct_7B().pack(_x.use_ros_time, _x.enable_logging_imu, _x.enable_logging_temperature, _x.enable_logging_magnetic_field, _x.enable_logging_pressure, _x.enable_logging_battery, _x.enable_logging_packets))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.log_blocks is None:
        self.log_blocks = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.uri = str[start:end].decode('utf-8')
      else:
        self.uri = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tf_prefix = str[start:end].decode('utf-8')
      else:
        self.tf_prefix = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.roll_trim, _x.pitch_trim, _x.enable_logging, _x.enable_parameters,) = _get_struct_2f2B().unpack(str[start:end])
      self.enable_logging = bool(self.enable_logging)
      self.enable_parameters = bool(self.enable_parameters)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.log_blocks = []
      for i in range(0, length):
        val1 = crazyflie_driver.msg.LogBlock()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.topic_name = str[start:end].decode('utf-8')
        else:
          val1.topic_name = str[start:end]
        start = end
        end += 2
        (val1.frequency,) = _get_struct_h().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.variables = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8')
          else:
            val2 = str[start:end]
          val1.variables.append(val2)
        self.log_blocks.append(val1)
      _x = self
      start = end
      end += 7
      (_x.use_ros_time, _x.enable_logging_imu, _x.enable_logging_temperature, _x.enable_logging_magnetic_field, _x.enable_logging_pressure, _x.enable_logging_battery, _x.enable_logging_packets,) = _get_struct_7B().unpack(str[start:end])
      self.use_ros_time = bool(self.use_ros_time)
      self.enable_logging_imu = bool(self.enable_logging_imu)
      self.enable_logging_temperature = bool(self.enable_logging_temperature)
      self.enable_logging_magnetic_field = bool(self.enable_logging_magnetic_field)
      self.enable_logging_pressure = bool(self.enable_logging_pressure)
      self.enable_logging_battery = bool(self.enable_logging_battery)
      self.enable_logging_packets = bool(self.enable_logging_packets)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.uri
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.tf_prefix
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f2B().pack(_x.roll_trim, _x.pitch_trim, _x.enable_logging, _x.enable_parameters))
      length = len(self.log_blocks)
      buff.write(_struct_I.pack(length))
      for val1 in self.log_blocks:
        _x = val1.topic_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_h().pack(val1.frequency))
        length = len(val1.variables)
        buff.write(_struct_I.pack(length))
        for val2 in val1.variables:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.pack('<I%ss'%length, length, val2))
      _x = self
      buff.write(_get_struct_7B().pack(_x.use_ros_time, _x.enable_logging_imu, _x.enable_logging_temperature, _x.enable_logging_magnetic_field, _x.enable_logging_pressure, _x.enable_logging_battery, _x.enable_logging_packets))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.log_blocks is None:
        self.log_blocks = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.uri = str[start:end].decode('utf-8')
      else:
        self.uri = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tf_prefix = str[start:end].decode('utf-8')
      else:
        self.tf_prefix = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.roll_trim, _x.pitch_trim, _x.enable_logging, _x.enable_parameters,) = _get_struct_2f2B().unpack(str[start:end])
      self.enable_logging = bool(self.enable_logging)
      self.enable_parameters = bool(self.enable_parameters)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.log_blocks = []
      for i in range(0, length):
        val1 = crazyflie_driver.msg.LogBlock()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.topic_name = str[start:end].decode('utf-8')
        else:
          val1.topic_name = str[start:end]
        start = end
        end += 2
        (val1.frequency,) = _get_struct_h().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.variables = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8')
          else:
            val2 = str[start:end]
          val1.variables.append(val2)
        self.log_blocks.append(val1)
      _x = self
      start = end
      end += 7
      (_x.use_ros_time, _x.enable_logging_imu, _x.enable_logging_temperature, _x.enable_logging_magnetic_field, _x.enable_logging_pressure, _x.enable_logging_battery, _x.enable_logging_packets,) = _get_struct_7B().unpack(str[start:end])
      self.use_ros_time = bool(self.use_ros_time)
      self.enable_logging_imu = bool(self.enable_logging_imu)
      self.enable_logging_temperature = bool(self.enable_logging_temperature)
      self.enable_logging_magnetic_field = bool(self.enable_logging_magnetic_field)
      self.enable_logging_pressure = bool(self.enable_logging_pressure)
      self.enable_logging_battery = bool(self.enable_logging_battery)
      self.enable_logging_packets = bool(self.enable_logging_packets)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f2B = None
def _get_struct_2f2B():
    global _struct_2f2B
    if _struct_2f2B is None:
        _struct_2f2B = struct.Struct("<2f2B")
    return _struct_2f2B
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie_driver/AddCrazyflieResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AddCrazyflieResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "crazyflie_driver/AddCrazyflieResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddCrazyflieResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class AddCrazyflie(object):
  _type          = 'crazyflie_driver/AddCrazyflie'
  _md5sum = '34565a892f53e550eb958f2ab393aeee'
  _request_class  = AddCrazyflieRequest
  _response_class = AddCrazyflieResponse
