// Generated by gencpp from file crazyflie_driver/Land.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_LAND_H
#define CRAZYFLIE_DRIVER_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <crazyflie_driver/LandRequest.h>
#include <crazyflie_driver/LandResponse.h>


namespace crazyflie_driver
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::Land > {
  static const char* value()
  {
    return "b665b6c83a196e4774268cc26329b159";
  }

  static const char* value(const ::crazyflie_driver::Land&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::Land > {
  static const char* value()
  {
    return "crazyflie_driver/Land";
  }

  static const char* value(const ::crazyflie_driver::Land&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::LandRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Land > 
template<>
struct MD5Sum< ::crazyflie_driver::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Land >::value();
  }
  static const char* value(const ::crazyflie_driver::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::LandRequest> should match 
// service_traits::DataType< ::crazyflie_driver::Land > 
template<>
struct DataType< ::crazyflie_driver::LandRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Land >::value();
  }
  static const char* value(const ::crazyflie_driver::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::LandResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Land > 
template<>
struct MD5Sum< ::crazyflie_driver::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Land >::value();
  }
  static const char* value(const ::crazyflie_driver::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::LandResponse> should match 
// service_traits::DataType< ::crazyflie_driver::Land > 
template<>
struct DataType< ::crazyflie_driver::LandResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Land >::value();
  }
  static const char* value(const ::crazyflie_driver::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_LAND_H
