// Generated by gencpp from file crazyflie_driver/RemoveCrazyflie.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_REMOVECRAZYFLIE_H
#define CRAZYFLIE_DRIVER_MESSAGE_REMOVECRAZYFLIE_H

#include <ros/service_traits.h>


#include <crazyflie_driver/RemoveCrazyflieRequest.h>
#include <crazyflie_driver/RemoveCrazyflieResponse.h>


namespace crazyflie_driver
{

struct RemoveCrazyflie
{

typedef RemoveCrazyflieRequest Request;
typedef RemoveCrazyflieResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveCrazyflie
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::RemoveCrazyflie > {
  static const char* value()
  {
    return "636fe5e07550f026d28388e95c38a9f4";
  }

  static const char* value(const ::crazyflie_driver::RemoveCrazyflie&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::RemoveCrazyflie > {
  static const char* value()
  {
    return "crazyflie_driver/RemoveCrazyflie";
  }

  static const char* value(const ::crazyflie_driver::RemoveCrazyflie&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::RemoveCrazyflieRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::RemoveCrazyflie > 
template<>
struct MD5Sum< ::crazyflie_driver::RemoveCrazyflieRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::RemoveCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_driver::RemoveCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::RemoveCrazyflieRequest> should match 
// service_traits::DataType< ::crazyflie_driver::RemoveCrazyflie > 
template<>
struct DataType< ::crazyflie_driver::RemoveCrazyflieRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::RemoveCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_driver::RemoveCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::RemoveCrazyflieResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::RemoveCrazyflie > 
template<>
struct MD5Sum< ::crazyflie_driver::RemoveCrazyflieResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::RemoveCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_driver::RemoveCrazyflieResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::RemoveCrazyflieResponse> should match 
// service_traits::DataType< ::crazyflie_driver::RemoveCrazyflie > 
template<>
struct DataType< ::crazyflie_driver::RemoveCrazyflieResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::RemoveCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_driver::RemoveCrazyflieResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_REMOVECRAZYFLIE_H
