// Generated by gencpp from file crazyflie_driver/sendPacket.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_SENDPACKET_H
#define CRAZYFLIE_DRIVER_MESSAGE_SENDPACKET_H

#include <ros/service_traits.h>


#include <crazyflie_driver/sendPacketRequest.h>
#include <crazyflie_driver/sendPacketResponse.h>


namespace crazyflie_driver
{

struct sendPacket
{

typedef sendPacketRequest Request;
typedef sendPacketResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendPacket
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::sendPacket > {
  static const char* value()
  {
    return "e3f946ce194c915d34d0f5ddedef0de7";
  }

  static const char* value(const ::crazyflie_driver::sendPacket&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::sendPacket > {
  static const char* value()
  {
    return "crazyflie_driver/sendPacket";
  }

  static const char* value(const ::crazyflie_driver::sendPacket&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::sendPacketRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::sendPacket > 
template<>
struct MD5Sum< ::crazyflie_driver::sendPacketRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::sendPacket >::value();
  }
  static const char* value(const ::crazyflie_driver::sendPacketRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::sendPacketRequest> should match 
// service_traits::DataType< ::crazyflie_driver::sendPacket > 
template<>
struct DataType< ::crazyflie_driver::sendPacketRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::sendPacket >::value();
  }
  static const char* value(const ::crazyflie_driver::sendPacketRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::sendPacketResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::sendPacket > 
template<>
struct MD5Sum< ::crazyflie_driver::sendPacketResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::sendPacket >::value();
  }
  static const char* value(const ::crazyflie_driver::sendPacketResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::sendPacketResponse> should match 
// service_traits::DataType< ::crazyflie_driver::sendPacket > 
template<>
struct DataType< ::crazyflie_driver::sendPacketResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::sendPacket >::value();
  }
  static const char* value(const ::crazyflie_driver::sendPacketResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_SENDPACKET_H
