// Generated by gencpp from file crazyflie_driver/Stop.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_STOP_H
#define CRAZYFLIE_DRIVER_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <crazyflie_driver/StopRequest.h>
#include <crazyflie_driver/StopResponse.h>


namespace crazyflie_driver
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::Stop > {
  static const char* value()
  {
    return "d44d7e9aa94d069ed5834dbd7329e1bb";
  }

  static const char* value(const ::crazyflie_driver::Stop&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::Stop > {
  static const char* value()
  {
    return "crazyflie_driver/Stop";
  }

  static const char* value(const ::crazyflie_driver::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::StopRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Stop > 
template<>
struct MD5Sum< ::crazyflie_driver::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Stop >::value();
  }
  static const char* value(const ::crazyflie_driver::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::StopRequest> should match 
// service_traits::DataType< ::crazyflie_driver::Stop > 
template<>
struct DataType< ::crazyflie_driver::StopRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Stop >::value();
  }
  static const char* value(const ::crazyflie_driver::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::StopResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Stop > 
template<>
struct MD5Sum< ::crazyflie_driver::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Stop >::value();
  }
  static const char* value(const ::crazyflie_driver::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::StopResponse> should match 
// service_traits::DataType< ::crazyflie_driver::Stop > 
template<>
struct DataType< ::crazyflie_driver::StopResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Stop >::value();
  }
  static const char* value(const ::crazyflie_driver::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_STOP_H
