// Generated by gencpp from file crazyflie_driver/Takeoff.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_TAKEOFF_H
#define CRAZYFLIE_DRIVER_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <crazyflie_driver/TakeoffRequest.h>
#include <crazyflie_driver/TakeoffResponse.h>


namespace crazyflie_driver
{

struct Takeoff
{

typedef TakeoffRequest Request;
typedef TakeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Takeoff
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::Takeoff > {
  static const char* value()
  {
    return "b665b6c83a196e4774268cc26329b159";
  }

  static const char* value(const ::crazyflie_driver::Takeoff&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::Takeoff > {
  static const char* value()
  {
    return "crazyflie_driver/Takeoff";
  }

  static const char* value(const ::crazyflie_driver::Takeoff&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::TakeoffRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Takeoff > 
template<>
struct MD5Sum< ::crazyflie_driver::TakeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Takeoff >::value();
  }
  static const char* value(const ::crazyflie_driver::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::TakeoffRequest> should match 
// service_traits::DataType< ::crazyflie_driver::Takeoff > 
template<>
struct DataType< ::crazyflie_driver::TakeoffRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Takeoff >::value();
  }
  static const char* value(const ::crazyflie_driver::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::TakeoffResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::Takeoff > 
template<>
struct MD5Sum< ::crazyflie_driver::TakeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::Takeoff >::value();
  }
  static const char* value(const ::crazyflie_driver::TakeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::TakeoffResponse> should match 
// service_traits::DataType< ::crazyflie_driver::Takeoff > 
template<>
struct DataType< ::crazyflie_driver::TakeoffResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::Takeoff >::value();
  }
  static const char* value(const ::crazyflie_driver::TakeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_TAKEOFF_H
