// Generated by gencpp from file crazyflie_driver/UploadTrajectory.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_UPLOADTRAJECTORY_H
#define CRAZYFLIE_DRIVER_MESSAGE_UPLOADTRAJECTORY_H

#include <ros/service_traits.h>


#include <crazyflie_driver/UploadTrajectoryRequest.h>
#include <crazyflie_driver/UploadTrajectoryResponse.h>


namespace crazyflie_driver
{

struct UploadTrajectory
{

typedef UploadTrajectoryRequest Request;
typedef UploadTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadTrajectory
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::UploadTrajectory > {
  static const char* value()
  {
    return "becd7733dfdc3d0c93a9064ba651cf17";
  }

  static const char* value(const ::crazyflie_driver::UploadTrajectory&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::UploadTrajectory > {
  static const char* value()
  {
    return "crazyflie_driver/UploadTrajectory";
  }

  static const char* value(const ::crazyflie_driver::UploadTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::UploadTrajectoryRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::UploadTrajectory > 
template<>
struct MD5Sum< ::crazyflie_driver::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::UploadTrajectoryRequest> should match 
// service_traits::DataType< ::crazyflie_driver::UploadTrajectory > 
template<>
struct DataType< ::crazyflie_driver::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::UploadTrajectoryResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::UploadTrajectory > 
template<>
struct MD5Sum< ::crazyflie_driver::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::UploadTrajectoryResponse> should match 
// service_traits::DataType< ::crazyflie_driver::UploadTrajectory > 
template<>
struct DataType< ::crazyflie_driver::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_UPLOADTRAJECTORY_H
